version: 2
jobs:
  lerna_publish:
    docker:
      - image: circleci/node:20
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - docker-{{ .Branch }}
            - yarn-{{ .Branch }}
      - run:
          name: Place NPM registry token
          command: echo -e "//registry.npmjs.org/:_authToken=$NPMTOKEN \nscope=shepherdorg \naccess=public" > ~/.npmrc
      - run:
          name: Set yarn cache location
          command: yarn config set cache-folder ~/.cache/yarn
      - run:
          name: Yarn install
          command: yarn install --frozen-lockfile --check-files
      - run:
          name: Bootstrap
          command: yarn bootstrap
      - run:
          name: Build
          command: yarn build
      - save_cache:
          key: yarn-{{ .Branch }}-{{ epoch }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Publish to NPM
          command: yarn run lerna publish from-package --yes
#      - run:
#          name: Restore docker layer restore
#          command: |
#            set +o pipefail
#            docker load -i /tmp/layercache.tar | true
#      - run:
#          name: Login to docker registry
#          command: docker login -u $DOCKER_USER -p $DOCKER_PASSWD
#      - run:
#          name: Build docker images
#          command: BASE_COMMIT=$(./scripts/base-commit.sh) BUILD_NUMBER=$CIRCLE_BUILD_NUM ./scripts/build.js --only-changed
#      - run:
#          name: Push docker images
#          command: BASE_COMMIT=$(./scripts/base-commit.sh) BUILD_NUMBER=$CIRCLE_BUILD_NUM ./scripts/deploy-docker.js --only-changed
#      - run:
#          name: Save Docker Layer Cache
#          command: BASE_COMMIT=$(./scripts/base-commit.sh) ./scripts/save-docker-cache.js --only-changed > /tmp/layercache.tar
#      - save_cache:
#          key: docker-{{ .Branch }}-{{ epoch }}
#          paths:
#            - /tmp/layercache.tar
  build_and_test:
    docker:
      - image: circleci/node:20
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - docker-{{ .Branch }}
            - yarn-{{ .Branch }}
      - run:
          name: Set yarn cache location
          command: yarn config set cache-folder ~/.cache/yarn
      - run:
          name: Yarn install
          command: yarn install --frozen-lockfile --check-files
      - run:
          name: Bootstrap
          command: yarn bootstrap
      - save_cache:
          key: yarn-{{ .Branch }}-{{ epoch }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Build
          command: yarn build
      - run:
          name: Run unit tests
          command: yarn test
workflows:
  version: 2
  publish:
    jobs:
      - lerna_publish:
          filters:
            branches:
              only: master
  build_only:
    jobs:
      - build_and_test:
          filters:
            branches:
              ignore: master
